import Head from 'next/head'
import ProfileCardInfo from '../components/ProfileCardInfo'
import HomeSection from '../components/HomeSection'

export default function Home() {
  return (
    <div className='bg-[#121212] pb-20  lg:pb-16 lg:py-10 md:py-16 py-4 '>
      <Head>
        <title>Rohit s Protfolio</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <div className=' flex lg:flex-row md:flex-col lg:px-16 md:px-16 px-4 flex-col gap-10 justify-center'>
        <ProfileCardInfo />
        <HomeSection />
      </div>
    </div>
  )
}
